-- SQL Workbook

-- 2.1 SELECT
SELECT * FROM Employee;
SELECT * FROM Employee
  WHERE LASTNAME='King';
SELECT * FROM Employee
  WHERE FIRSTNAME='Andrew' AND REPORTSTO IS NULL;
SELECT * FROM Album order by title desc;

-- 2.2 ORDER BY
SELECT * FROM Album
  ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM Customer
  ORDER BY FIRSTNAME ASC;

-- 2.3 INSERT INTO
INSERT INTO genre VALUES (26, 'Chillstep');
INSERT INTO genre VALUES (27, 'Dubstep');
INSERT INTO Empoyee (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, EMAIL)
  VALUES (9, 'Thomas', 'Robert', 'Regional Manager', 'bob@gthomas.com');
INSERT INTO Employee (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, EMAIL)
  VALUES (10, 'Milton', 'Jones', 'HR Officer', 'Milton@Jones.com');
INSERT INTO Customer (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL)
  VALUES (53, 'Jane', 'Doe', 'janen@doe.com');
INSERT INTO Customer (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL)
  VALUES (54, 'Jim', 'Jacobs', 'jim@jacobs.com');

--2.4 UPDATE
UPDATE Customer SET FIRSTNAME='Robert', LASTNAME='Walter'
  WHERE FIRSTNAME='Aaron' AND LASTNAME='Mitchell';
UPDATE Artist SET NAME='CCR' 
  WHERE ARTISTID = 76;

-- 2.5 LIKE
SELECT * FROM Invoice WHERE BILLINGADDRESS LIKE 'T%';

-- 2.6 BETWEEN
SELECT * FROM Invoice
  WHERE TOTAL BETWEEN 15 AND 50;
SELECT * FROM Employee
  WHERE HIREDATE BETWEEN '1-JUN-03' AND '1-MAR-04';

-- 2.7 DELETE
DELETE FROM Customer WHERE FIRSTNAME='Robert' AND LASTNAME='Walter';

-- 3.1
CREATE OR REPLACE FUNCTION currentTime RETURN TIMESTAMP
IS thetime TIMESTAMP;
BEGIN
  SELECT CURRENT_TIMESTAMP INTO currentTime FROM DUAL;
  RETURN thetime;
END;

-- 4.1
CREATE OR REPLACE PROCEDURE getNames(e_cursor OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN e_cursor FOR
  SELECT FIRSTNAME, LASTNAME FROM Employee;
END;

-- 6.1 TRIGGER 
-- Create a trigger for row delete on customer table
CREATE OR REPLACE TRIGGER customerDelete
AFTER DELETE
ON CUSTOMER
FOR EACH ROW
BEGIN
  DBMS_OUTPUT.PUT_LINE('Customer deleted complete.');
END;

--7.1 INNER JOIN
SELECT cust.FIRSTNAME, cust.LASTNAME, invoi.INVOICEID
FROM Customer cust INNER JOIN Invoice invoi ON
cust.CUSTOMERID = invoi.CUSTOMERID
ORDER BY cust.LASTNAME ASC;

--7.2 OUTER JOIN
SELECT cust.CUSTOMERID, cust.FIRSTNAME, cust.LASTNAME, invoi.INVOICEID, invoi.TOTAL
  FROM Customer cust FULL OUTER JOIN INVOICE invoi
  ON cust.CUSTOMERID = invoi.INVOICEID;

--7.3 RIGHT JOIN
SELECT arts.NAME, alb.TITLE
FROM Artist arts RIGHT JOIN Album alb
  ON arts.ARTISTID = alb.ARTISTID;

--7.4 - CROSS JOIN
SELECT arts.NAME, alb.TITLE FROM Album alb
  CROSS JOIN ARTIST arts
  ORDER BY arts.NAME ASC;