DESCRIBE ARTIST;

/* DISPLAYING ARTIST NAMES THAT START WITH R */
SELECT NAME FROM ARTIST WHERE NAME LIKE 'R%';

DESCRIBE CUSTOMER;

/* CHECKING FIRSTNAMES THAT REPEAT MORE THAN ONCE */
SELECT FIRSTNAME, COUNT(FIRSTNAME) AS REPEATING 
FROM CUSTOMER
GROUP BY FIRSTNAME
HAVING COUNT(FIRSTNAME) > 1
ORDER BY REPEATING DESC;

/* CUSTOMERS THAT HAVE SPENT MORE THAN 45 DOLLARS */
SELECT C.FIRSTNAME, C.LASTNAME, SUM(I.TOTAL) AS AMOUNT_SPENT_LIFE_TIME, ROUND(AVG(I.TOTAL), 4) AS AVERAGE_AMOUNT
FROM INVOICE I, CUSTOMER C
WHERE I.CUSTOMERID = C.CUSTOMERID
GROUP BY (C.FIRSTNAME, C.LASTNAME)
HAVING SUM(I.TOTAL) > 45
ORDER BY AMOUNT_SPENT_LIFE_TIME DESC;




