/* Only books with authors */
SELECT (A.A_FIRST_NAME || ', ' || A.A_LAST_NAME) AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A INNER JOIN BOOK B
ON A.A_ID = B.A_ID;

/* Books with no authors */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A RIGHT JOIN BOOK B
ON A.A_ID = B.A_ID;

/* Authors with no books */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A LEFT JOIN BOOK B
ON A.A_ID = B.A_ID;

/* Authors with no books AND Books with no authors */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A FULL JOIN BOOK B
ON A.A_ID = B.A_ID;

/* Removing the inner part */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A RIGHT JOIN BOOK B
ON A.A_ID = B.A_ID
WHERE A.A_FIRST_NAME IS NULL;

/** DUMMY TABLE **/
SELECT TO_CHAR(SYSDATE,'HH') FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;

/** JOINS THE PRO WAY **/
/* Books with no authors */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A, BOOK B
WHERE A.A_ID = B.A_ID(+);

/* Authors with no books */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A, BOOK B
WHERE A.A_ID(+) = B.A_ID;

/*** Authors with no books AND Books with no authors (Whoops) ***/
/* 1 - This didn't work */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A, BOOK B
WHERE A.A_ID(+) = B.A_ID(+);

/* 2 - This will work */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A, BOOK B
WHERE A.A_ID = B.A_ID(+)
UNION
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A, BOOK B
WHERE A.A_ID(+) = B.A_ID;


/* Removing the inner part */
SELECT A.A_FIRST_NAME AS AUTHOR_NAME, B.B_TITLE AS BOOK_TITLE
FROM AUTHOR A, BOOK B
WHERE A.A_ID(+) = B.A_ID 
AND A.A_FIRST_NAME IS NULL;

